# Generated by Django 4.2.11 on 2024-06-18 04:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_lastname_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='image_url',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image',
            field=cloudinary.models.CloudinaryField(default='path/to/placeholder/image.jpg', max_length=255, verbose_name='image'),
        ),
    ]
